### ISSUE TITLE
Often error... and work stop

### ISSUE THREAD

**Issue by ManuelPeiro** [cyborgcnc/CYBORGCNC__RRVC3MOD#9]
Hi.

After a while using the SHT 42 board... I have to say that it is an upgrade that I consider INDISPENSABLE.
It changes a lot from carrying a bundle of approximately 10 cables, to carrying only 3... 
Now, not everything is perfect. The problem that I find is that very often, more than expected, the printing fails due to lack of communication between the SHT and the main board, giving me this error.."MC 'extruder' reports error: GSTAT: 00000001 reset=1( Reset)"... 

I have connected the SHT via USB to the Rpi... I have tried different USBs cables, in case it was that, and so far nothing. 

If I used the UTOC board,do you think would this be solved?
Or other idea apreciated

**Comment by cyborgcnc** [comment]
I have been using the tool board for a few months now, and I have not had a single  issue after many hours  of printing.  I am NOT using the USB cable.  I am using the CAN-USB adapter (UTOC), and I am using the CAN wires to connect the Rpi to the tool board.  I have heard other people having issues with USB, so I would consider using a USB to CAN bus adapter to see if it makes a difference, or fixes your issue.

**Comment by ManuelPeiro** [comment]
only Mellow models UTOC 1 and 3 are suitable for tool board? or can use another?

**Comment by cyborgcnc** [comment]
I am using the Mellow UTOC, I have not used another one, so I do not know.  I would think, that since the CAN protocol IS a standard, any other USB to CAN converter  will more than likely work.  The key would be that the product has drivers for  the RaspberryPi, and it is recognized  as a  port.   If this is the case, than more than likely it will work.
